
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:8 (project)"
    message: |
      The target system is: WASI -  - wasm32
      The host system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:8 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/wasi-sdk/bin/clang.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is Clang, found in:
        F:/Workspace/Penny/src/penny-core/out/CMakeFiles/4.0.2/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:8 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "F:/Workspace/Penny/src/penny-core/out/CMakeFiles/CMakeScratch/TryCompile-sukdxr"
      binary: "F:/Workspace/Penny/src/penny-core/out/CMakeFiles/CMakeScratch/TryCompile-sukdxr"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'F:/Workspace/Penny/src/penny-core/out/CMakeFiles/CMakeScratch/TryCompile-sukdxr'
        
        Run Build Command(s): C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 C:/Strawberry/c/bin/gmake.exe -f Makefile cmTC_9d3b5/fast
        C:/Strawberry/c/bin/gmake.exe  -f CMakeFiles/cmTC_9d3b5.dir/build.make CMakeFiles/cmTC_9d3b5.dir/build
        gmake[1]: Entering directory 'F:/Workspace/Penny/src/penny-core/out/CMakeFiles/CMakeScratch/TryCompile-sukdxr'
        Building C object CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj
        C:/wasi-sdk/bin/clang.exe   -fansi-escape-codes -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj -c C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeCCompilerABI.c
        clang version 21.1.4 (https://github.com/llvm/llvm-project 222fc11f2b8f25f6a0f4976272ef1bb7bf49521d)
        Target: wasm32-unknown-wasi
        Thread model: posix
        InstalledDir: C:\\wasi-sdk\\bin
        Configuration file: C:\\wasi-sdk\\bin\\clang.cfg
         (in-process)
         "C:\\\\wasi-sdk\\\\bin\\\\clang.exe" -cc1 -triple wasm32-unknown-wasi -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility=hidden -debugger-tuning=gdb "-fdebug-compilation-dir=F:\\\\Workspace\\\\Penny\\\\src\\\\penny-core\\\\out\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-sukdxr" -v "-fcoverage-compilation-dir=F:\\\\Workspace\\\\Penny\\\\src\\\\penny-core\\\\out\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-sukdxr" -resource-dir "C:\\\\wasi-sdk\\\\lib\\\\clang\\\\21" -dependency-file CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj.d -MT CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj -sys-header-deps -isysroot "C:\\\\wasi-sdk\\\\bin/../share/wasi-sysroot" -internal-isystem "C:\\\\wasi-sdk\\\\lib\\\\clang\\\\21\\\\include" -internal-isystem "C:\\\\wasi-sdk\\\\bin/../share/wasi-sysroot/include/wasm32-wasi" -internal-isystem "C:\\\\wasi-sdk\\\\bin/../share/wasi-sysroot/include" -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcolor-diagnostics -fansi-escape-codes -o CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj -x c C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeCCompilerABI.c
        clang -cc1 version 21.1.4 based upon LLVM 21.1.4 default target wasm32-wasi
        #include "..." search starts here:
        #include <...> search starts here:
         C:\\wasi-sdk\\lib\\clang\\21\\include
         C:\\wasi-sdk\\bin/../share/wasi-sysroot/include/wasm32-wasi
         C:\\wasi-sdk\\bin/../share/wasi-sysroot/include
        End of search list.
        Linking C static library libcmTC_9d3b5.a
        C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -P CMakeFiles/cmTC_9d3b5.dir/cmake_clean_target.cmake
        C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E cmake_link_script CMakeFiles/cmTC_9d3b5.dir/link.txt --verbose=1
        C:/wasi-sdk/bin/llvm-ar.exe qc libcmTC_9d3b5.a CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj
        C:/wasi-sdk/bin/llvm-ranlib.exe libcmTC_9d3b5.a
        gmake[1]: Leaving directory 'F:/Workspace/Penny/src/penny-core/out/CMakeFiles/CMakeScratch/TryCompile-sukdxr'
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:191 (message)"
      - "C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:8 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [C:/wasi-sdk/lib/clang/21/include]
          add: [C:/wasi-sdk/bin/../share/wasi-sysroot/include/wasm32-wasi]
          add: [C:/wasi-sdk/bin/../share/wasi-sysroot/include]
        end of search list found
        collapse include dir [C:/wasi-sdk/lib/clang/21/include] ==> [C:/wasi-sdk/lib/clang/21/include]
        collapse include dir [C:/wasi-sdk/bin/../share/wasi-sysroot/include/wasm32-wasi] ==> [C:/wasi-sdk/share/wasi-sysroot/include/wasm32-wasi]
        collapse include dir [C:/wasi-sdk/bin/../share/wasi-sysroot/include] ==> [C:/wasi-sdk/share/wasi-sysroot/include]
        implicit include dirs: [C:/wasi-sdk/lib/clang/21/include;C:/wasi-sdk/share/wasi-sysroot/include/wasm32-wasi;C:/wasi-sdk/share/wasi-sysroot/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:8 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)))("|,| |$)]
        ignore line: [Change Dir: 'F:/Workspace/Penny/src/penny-core/out/CMakeFiles/CMakeScratch/TryCompile-sukdxr']
        ignore line: []
        ignore line: [Run Build Command(s): C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 C:/Strawberry/c/bin/gmake.exe -f Makefile cmTC_9d3b5/fast]
        ignore line: [C:/Strawberry/c/bin/gmake.exe  -f CMakeFiles/cmTC_9d3b5.dir/build.make CMakeFiles/cmTC_9d3b5.dir/build]
        ignore line: [gmake[1]: Entering directory 'F:/Workspace/Penny/src/penny-core/out/CMakeFiles/CMakeScratch/TryCompile-sukdxr']
        ignore line: [Building C object CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj]
        ignore line: [C:/wasi-sdk/bin/clang.exe   -fansi-escape-codes -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj -c C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeCCompilerABI.c]
        ignore line: [clang version 21.1.4 (https://github.com/llvm/llvm-project 222fc11f2b8f25f6a0f4976272ef1bb7bf49521d)]
        ignore line: [Target: wasm32-unknown-wasi]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: C:\\wasi-sdk\\bin]
        ignore line: [Configuration file: C:\\wasi-sdk\\bin\\clang.cfg]
        ignore line: [ (in-process)]
        ignore line: [ "C:\\\\wasi-sdk\\\\bin\\\\clang.exe" -cc1 -triple wasm32-unknown-wasi -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility=hidden -debugger-tuning=gdb "-fdebug-compilation-dir=F:\\\\Workspace\\\\Penny\\\\src\\\\penny-core\\\\out\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-sukdxr" -v "-fcoverage-compilation-dir=F:\\\\Workspace\\\\Penny\\\\src\\\\penny-core\\\\out\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-sukdxr" -resource-dir "C:\\\\wasi-sdk\\\\lib\\\\clang\\\\21" -dependency-file CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj.d -MT CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj -sys-header-deps -isysroot "C:\\\\wasi-sdk\\\\bin/../share/wasi-sysroot" -internal-isystem "C:\\\\wasi-sdk\\\\lib\\\\clang\\\\21\\\\include" -internal-isystem "C:\\\\wasi-sdk\\\\bin/../share/wasi-sysroot/include/wasm32-wasi" -internal-isystem "C:\\\\wasi-sdk\\\\bin/../share/wasi-sysroot/include" -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcolor-diagnostics -fansi-escape-codes -o CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj -x c C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeCCompilerABI.c]
        ignore line: [clang -cc1 version 21.1.4 based upon LLVM 21.1.4 default target wasm32-wasi]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ C:\\wasi-sdk\\lib\\clang\\21\\include]
        ignore line: [ C:\\wasi-sdk\\bin/../share/wasi-sysroot/include/wasm32-wasi]
        ignore line: [ C:\\wasi-sdk\\bin/../share/wasi-sysroot/include]
        ignore line: [End of search list.]
        ignore line: [Linking C static library libcmTC_9d3b5.a]
        ignore line: [C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -P CMakeFiles/cmTC_9d3b5.dir/cmake_clean_target.cmake]
        ignore line: [C:/Users/joydm/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E cmake_link_script CMakeFiles/cmTC_9d3b5.dir/link.txt --verbose=1]
        ignore line: [C:/wasi-sdk/bin/llvm-ar.exe qc libcmTC_9d3b5.a CMakeFiles/cmTC_9d3b5.dir/CMakeCCompilerABI.c.obj]
        ignore line: [C:/wasi-sdk/bin/llvm-ranlib.exe libcmTC_9d3b5.a]
        ignore line: [gmake[1]: Leaving directory 'F:/Workspace/Penny/src/penny-core/out/CMakeFiles/CMakeScratch/TryCompile-sukdxr']
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
